# SPDX-FileCopyrightText: 2024 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[workspace]
members = ["serde_list", "serde_list/serde_list_macros"]

[package]
name = "mimi_content"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
ciborium = "0.2.2"
hex = "0.4.3"
serde = { version = "1.0.215", features = ["derive"] }
serde_bytes = "0.11.15"
serde_list = { path = "./serde_list" }
sha2 = "0.10.9"
thiserror = "2.0.11"
